### ISSUE TITLE
Defect : MoveTo only accept the offset value.

### ISSUE THREAD

**Issue by EthanJiang** [appium/dotnet-client#116]
Hi 

If I want to do this  Press（100， 1070） then Move to （500， 1000）， then (20, 300)

In code, I need to write as  androiddriver.Press(100, 1070).MoveTo(500 - 100, 1000 - 1070).MoveTo(20 - 500, 300 - 100).Release().

but the release action will do touchup on (20 - 500, 300 - 1000). 

So something wrong with the MoveTo or Release 

Server log.

tion":"moveTo","options":{"x":-480,"y":-700}},{"action":"release"}]}
info: [debug] Pushing command to appium work queue: ["element:touchDown",{"x":100,"y":1070}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":100,"y":1070}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchDown
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1200,1823]
info: [debug] [BOOTSTRAP] [debug] Performing TouchDown using element? false x: 100, y: 1070
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":500,"y":1000}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":500,"y":1000}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1200,1823]
info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 500, y: 1000
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":20,"y":300}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":20,"y":300}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1200,1823]
info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 20, y: 300
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchUp",{"x":-480,"y":-700}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":-480,"y":-700}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchUp
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1200,1823]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":29,"value":"Coordinate [x=-480.0, y=-700.0] is outside of element rect: [0,0][1200,1823]"}

**Comment by Dor-bl** [comment]
Hello @EthanJiang, thank you for your post.
I'm reviewing the open issues we currently have, can you please confirm this issue still reproduce for you? I see there has been a merge during that time that may have resolved your issue

**Comment by EthanJiang** [comment]
thanks
