### ISSUE TITLE
"Nested" FindElementsBy returns WebElements instead of WindowsElements

### ISSUE THREAD

**Issue by caulfield2** [appium/dotnet-client#188]
## Description

When using a nested search on a Windows application using WinAppDriver, a WebElement is returned instead of a WindowsElement.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium.WebDriver NuGet 3.0.0.3
* Desktop OS/version used to run Appium: Windows 7

Using WinAppDriver.exe with C# in VS 2015 to run tests on a Windows application in a Windows 10 VM.

## Details

My only experience with Appium is through using [WinAppDriver](https://github.com/Microsoft/WinAppDriver) to automate Windows applications, so I apologize in advance for any incorrect assumptions I make. I was recommended to post this here after originally posting to the WinAppDriver page [here](https://github.com/Microsoft/WinAppDriver/issues/237). 

I am trying to narrow down a search to a certain section of my app and then find all elements within that section by a certain name. In VS 2015, my initial thought was to do the following:

`driver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUri),`
`desktopCapabilities);`
`WindowsElement element = driver.FindElementByName("name1");`
`IList<WindowsElement> list = (IList<WindowsElement>)element.FindElementsByName("name2");`

I do not get any complaints in VS about this before I run my test. At runtime, I get the error below on the cast:

![image](https://user-images.githubusercontent.com/25783833/29522947-ceed5df8-8650-11e7-9423-ed301b26cc41.png)

Upon further inspection, it seems that `element.FindElementsByName("name2")` is returning type:

System.Collections.ObjectModel.ReadOnlyCollection<OpenQA.Selenium.Appium.AppiumWebElement>

which is why I am getting the cast exception. 

**Why is my nested search from a WindowsElement returning an AppiumWebElement?**

My workaround to this is to just replace

`IList<WindowsElement> list = (IList<WindowsElement>)element.FindElementsByName("name2");`

with 

`var list = element.FindElementsByName("name2");`
`list[0].Click();`

and I am able to click the desired element without issue. However, it doesn't make much sense that a WebElement should ever be returned, especially when my driver is instantiated as a `WindowsDriver<WindowsElement>`.

I am not sure if the error is because I am converting from a ReadOnlyCollection to an IList, or from WebElement to WindowsElement because

`WindowsElement element1 = driver.FindElementByName("name1");`
`WindowsElement element2 = (WindowsElement)element1.FindElementByName("name2").Click();`

executes without error as well, although the cast is needed which means that the "nesting" here is still returning a WebElement. Can someone confirm whether this is a valid concern? The way I see it, an explicit cast to a WindowsElement shouldn't be necessary when nesting a search like I do above.

**Comment by donschaefer** [comment]
Has anyone has found a solution to this issue yet? I recently ran into the same problem on a project I'm working on for a client & can't seem to find any other references to this issue online (aside from the handful of places issue has been posted/referenced). Thanks in advance for any followup!

**Comment by caulfield2** [comment]
@donschaefer I have yet to find a way to get a ReadOnlyCollection<WindowsElement> returned from a nested search and have not seen anyone else bring up this issue. Maybe posting this on the Appium repo would yield more insight.

**Comment by donschaefer** [comment]
Thanks for the response @caulfield2 - I ended up giving up on this too & ended up building out more complex xpath values as a work-around in the absence of a more elegant solution :(

**Comment by shaktim121** [comment]
Hello All,
I am still seeing the above issue and I think it is redirected to appium-dot-net-driver issue, but not yet fixed. 
It is critical for us to get a solution for this. Kindly help.

When we try to get nested FindElement or FindElements, it returns an appiumWebELement.

**Comment by mibs959** [comment]
Hi guys, any news regarding this issue?

**Comment by aeparras** [comment]
I encounter same issue, workaround I used is to cast appiumWebElement as WindowsElement

List<WindowsElement> listMatchingChildControls = new List<WindowsElement>();
ReadOnlyCollection<AppiumWebElement> controlCollection = someWinElementItem.FindElementsByName("AccessibleName");

foreach (AppiumWebElement childControl in controlCollection)
{
      WindowsElement winControl = childControl as WindowsElement;
      listMatchingChildControls.Add(winControl);
}

**Comment by Dor-bl** [comment]
@caulfield2 does the workaround suggested above worked for you?

**Comment by AmolLearning** [comment]
For nested elements declare element as AppiumWebelement the actions will be performed even if declare nested element as AppiumWebElement and other elements are declared as WindowsElement.

**Comment by Dor-bl** [comment]
Closed since no comment.
