### ISSUE TITLE
Execute unit tests as a part of CI process

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/dotnet-client#249]
We have to execute the set of basic unit and integration tests as a part of commit acceptance procedure.

**Comment by mykola-mokhnach** [comment]
Lets do the stuff step by step. Even one running integration test (but a stable one) would be very good. Also, unit test might be necessary for some custom helpers

**Comment by akinsolb** [comment]
Yeah i'm not sure if any unit tests exit atm or if they're merged into the integration test project. Will have a look an identify a test suite.

**Comment by Dor-bl** [comment]
@akinsolb should we change the milestone on this one?

**Comment by Dor-bl** [comment]
@mykola-mokhnach issue closed since it was handled under #557.
If you have other ideas on how to proceed from her, please let me know. I know you prefer GH actions over azure pipeline.
