### ISSUE TITLE
Add support for application management endpoints

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/dotnet-client#254]
https://github.com/appium/java-client/pull/824

**Comment by Dor-bl** [comment]
@mykola-mokhnach, please clarify what is missing from those endpoints in the dotnet client.
https://github.com/appium/dotnet-client/blob/main/src/Appium.Net/Appium/AppiumCommand.cs#L95C1-L104C69
https://github.com/appium/dotnet-client/blob/main/src/Appium.Net/Appium/AppiumCommand.cs#L131C1-L132C65

**Comment by mykola-mokhnach** [comment]
`/session/:sessionId/appium/device/app_state` seems to be missing

**Comment by Dor-bl** [comment]
Great, I'll send a PR to organize those endpoints and we can close this issue
