### ISSUE TITLE
Appium Server Timeout Issue

### ISSUE THREAD

**Issue by johnsajj** [appium/dotnet-client#401]
Good Morning,

Please assist, it has been years since I had to configure a Network Server and the first time I am working with Appium.  My thought is that the issues lies on my end with configuration and missing reference. I have tried to use the example and instruction given by Laolu Benson but I am missing step(s). Please see below information:

##Dev Environment

1. Visual Studio 2019
2. Appium WebDriver 4.1.1
3. Windows 10
4. Appium v1.15.1

## Details

An Appium Server has been configured on a Windows 10 and the Status is 'the Server is running'.  When running the Addition Test Method the following error occurs: 'The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session timed out after 30 seconds.'  The error occurs at Step 3

Step 1: Initialize the Appium Server 
_appiumServer = new AppiumServiceBuilder().Build(); //Defaults to localIP: 127.0.0.1 & port 4723
_appiumServer.Start();

Step 2: Added Code Logic to Add Additional Capabilities
AppiumOptions opt = new AppiumOptions();

opt.AddAdditionalCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
opt.AddAdditionalCapability("deviceName", "WindowsPC");			
opt.AddAdditionalCapability("platformName", "Windows");

Step 3: Called the Uri
private const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723/wd/hub";
private WindowsDriver<WindowsElement> _session;

 _session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt, TimeSpan.FromSeconds(30)); This is where the Error Occurs

This is the example given but there is a reference to 'Env' that I cannot Step through to understand the Code Logic:
 var serverUri = Env.ServerIsRemote() ? AppiumServers.RemoteServerUri : AppiumServers.LocalServiceUri;  _calculatorSession = new WindowsDriver<WindowsElement>(serverUri, appCapabilities,   Env.InitTimeoutSec);

## Exception stacktraces
Not familiar with how to do this

## Link to Appium logs
Not familiar with how to do this

Please contact me if additional information is needed.

Thank you for your patience and assistance in this matter,

Amina Johnson, AR
.Net Developer
Contractor, AFCEC/FMO
Inserso Corporation

**Comment by nadvolod** [comment]
I'm having the same exact issue. However, I'm not using `WindowsDriver` but `AndroidDriver`. I have several tests that you all can try [here](https://github.com/saucelabs-training/demo-csharp/blob/master/SauceExamples/DotnetFramework/Appium/Appium4.NUnit.Scripts/RealDevices/NativeApp/AndroidSimpleTests.cs). Feel free to pull the solution if that's helpful.

Appium WebDriver: 4.1.1
Selenium WebDriver: 3.141.0
OS: Windows 10

**Comment by johnsajj** [comment]
Thank you for providing the Code Logic. 

I have stepped through Code Logic provided and my thoughts for the root cause are:
        1.  Configuration
        2.  Authenticating|Authorization is not occurring

**Comment by johnsajj** [comment]
Please confirm nothing is needed on my end?  I have been tracking the progress of this issue since the end of March.

Thank you for your assistance in this matter

**Comment by Dor-bl** [comment]
@johnsajj can you please try with the new appium server version (2.0) and update?
Keep in mind you will need to use the beta version of this project in order to work with appium 2.0

**Comment by Dor-bl** [comment]
Closed since no response
