### ISSUE TITLE
missing XML documentation in nuget package

### ISSUE THREAD

**Issue by Beautyod** [appium/dotnet-client#441]
Dear team,

the file `Appium.Net.xml` is missing in the nuget package _Applium.Net_.

Without this file, you can't see the documentation of the methods, etc. inside of Visual Studio.
This makes programming more tricky. Especially for Appium newcomers.

It would be nice if you add the XML documentation file to the nuget package.
To build that file, you just need to set one checkbox in the build settings of _Release_.

By the way:
In the old nuget package name _appium-dotnet-driver_ there was an xml file available.

Thanks,
Andreas

**Comment by akinsolb** [comment]
Interesting. The last release was done via github. I'll look into it. Thanks

**Comment by Beautyod** [comment]
It took some time to figure out how to get the XML file into both build types (.NET Standard and Framework).
Now I got it, created a fork and a pull request (#442).

**Comment by akinsolb** [comment]
closed by #442
