### ISSUE TITLE
Android IME Actions Generation: mobile command 'performEditorAction' throws NotImplementedException

### ISSUE THREAD

**Issue by ChristopherKrishnan** [appium/dotnet-client#443]
## Description

The Appium documentation indicates support for generation IME actions (for example, pressing Search or Done button on the on-screen keyboard as described in these support pages:
http://appium.io/docs/en/commands/mobile-command/
http://appium.io/docs/en/writing-running-appium/android/android-ime/

However attempting to use this via C# throws a NotImplementedException - example when trying to generate the action for the Done button:

![image](https://user-images.githubusercontent.com/55400333/98539555-77733b00-2284-11eb-8b88-cbf5ad48b3ed.png)

## Environment

* .NET client: Appium.WebDriver 4.2.1
* Appium server version or git revision if you use some shapshot: 1.17.0
* Desktop OS/version used to run Appium if necessary: Windows 10 / Visual Studio 2019
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: N/A
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Google Pixel 2 emulator running Android 10. Issue also seen on Samsun S9 (Android 8.0) and Samsung Galaxy S4 (Android 8.1)

_NOTE_ If the issue is because of Appium version and someone knows which version I should specifically use to resolve this, kindlycomment

## Code To Reproduce Issue
```csharp
Driver.ExecuteScript("mobile:performEditorAction", new Dictionary<string, string> {{"action", "done" } });
 ```

## Exception stacktraces
https://gist.github.com/ChristopherKrishnan/dca3da9b211da053f9c0938cf456c80d

System.NotImplementedException
  HResult=0x80004001
  Message=Unknown mobile command "performEditorAction". Only shell,scrollBackTo,viewportScreenshot,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo commands are supported.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)

## Link to Appium logs
Sorry I'm not that familiar with how to get Appium logs when running Appium.NET in Visual Studio. I tried the following:

```csharp
var logs = Driver.Manage().Logs.GetLog("server");
 ```

But I get the following exception which I do not know how to resolve:

OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=An unknown server-side error occurred while processing the command. Original error: Appium server must have relaxed security flag set in order to be able to get server logs
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteLogs.GetLog(String logKind)

However I'm hoping the example code to reproduce the issue is simple enough for any investigation.

**Comment by mykola-mokhnach** [comment]
Your Appium server version is probably too old

**Comment by ChristopherKrishnan** [comment]
I quoted the Appium Server version which BrowserStack uses by default when it runs our tests - 1.17.0. We aren't explicitly setting a version to use, thus far there has been no need to - however recommendations on which version to use (one that works as part of Appium.NET 4.2.1) are welcome please.

**Comment by mykola-mokhnach** [comment]
I have doubts it's `1.17.0`, looks like a way older one. Please check with their customer support on which version is actually used there

**Comment by ChristopherKrishnan** [comment]
I've checked last communications we received, it is indeed 1.17.0. However I also see the issue locally when running a test from Visual Studio (Appium.NET 4.2.1) connected to an emulated Google Pixel 2 device loaded from Android Virtual Device Manager - here too no server version is being explicitly specified. Which Appium server version is used by default in this scenario?

(Please excuse the naïve questions, I'm not all that familiar with the various component versions and how they relate to each other in the grand scheme of things... )

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot advice nothing without the full log

**Comment by Dor-bl** [comment]
@ChristopherKrishnan Can you please give it a shot with the latest version of appium server? 2.x

**Comment by Dor-bl** [comment]
Closed as no response.
