### ISSUE TITLE
IOS click on a Browse Button results in no action

### ISSUE THREAD

**Issue by sushant0201** [appium/dotnet-client#456]
## Description

I have been trying to automate a scenario at my work. The scenario performs a click on a Browse Button button that causes a IOS dialog to be shown to browse for files to be used in a test. 

## Environment

I am using the Appium.Net nuget client version "4.3.1" in the code. The Appium server version is "1.20.1". This happens on both real device and iOS simulators.

## Details

I have used another webpage to reproduce the same issue as I cannot share the company's actual application. I can provide a sample code that I am trying.

## Code To Reproduce Issue [ Good To Have ]

var options = new AppiumOptions();           
options.AddAdditionalCapability(MobileCapabilityType.BrowserName, "Safari");
options.AddAdditionalCapability(MobileCapabilityType.PlatformName, "iOS");
options.AddAdditionalCapability("appium:deviceName", "iPhone XS Simulator");
options.AddAdditionalCapability("appium:platformVersion", "14.3");
IWebDriver webDriver = new IOSDriver<IWebElement>(executor, options);
webDriver.Navigate().GoToUrl("https://ps.uci.edu/~franklin/doc/file_upload.html");
IWebElement browseButton = webDriver.FindElement(By.XPath("//*[@name='userfile']"));
browseButton.Click();   //click doesn't seem to bring up the iOS dialogue to browse for files

## Workarounds tried
JavaScript click, Click using absolute xpath but nothing seems to open that iOS dialogue. If anyone has come across a similar issue, please provide any suggestions to try out.

**Comment by mykola-mokhnach** [comment]
You could try [safari driver](https://github.com/appium/appium-safari-driver) instead.

**Comment by sushant0201** [comment]
@mykola-mokhnach  are there c# examples to use safari driver? I can give it a try

**Comment by sushant0201** [comment]
@mykola-mokhnach  are there C# examples for using safari driver. I can give it a try if it is supported in C#.

**Comment by sushant0201** [comment]
@mykola-mokhnach is [appium safari driver](https://github.com/appium/appium-safari-driver) supported in C#. I see that the link mentions it supports JavaScript!

**Comment by KazuCocoa** [comment]
The implementation is JS as same as other Appium drivers, but you can use it with proper browserName and automationName capabilities like other drivers as well. https://github.com/appium/appium-safari-driver#example

**Comment by Dor-bl** [comment]
@sushant0201 did you managed with the examples provided?

**Comment by Dor-bl** [comment]
Closed as no response.

**Comment by pujagani** [comment]
@sushant0201 I understand this is an old issue. I was helping someone else regarding this and figured out a solution that works. Sharing it here in C# in case it helps someone:

```
           var driver = new IOSDriver(appiumServerUrl, capabilities);
            driver.Navigate().GoToUrl("https://ps.uci.edu/~franklin/doc/file_upload.html");
     
           driver.Context = "NATIVE_APP";
          
          string pg= driver.PageSource;
            Console.WriteLine(pg);
             
    IWebElement uploadInput = driver.FindElement(By.XPath("//XCUIElementTypeButton[@name='Choose File']"));
              uploadInput.Click();
  
            var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            AppiumElement gallery = driver.FindElement(By.XPath("//XCUIElementTypeButton[@name=\"Photo Library\"]"));
            gallery.Click(); 
           
            IWebElement photo = driver.FindElement(By.XPath("(//XCUIElementTypeImage[contains(@name,'Photo')])[1]"));
            photo.Click();
            driver.FindElement(By.XPath("//XCUIElementTypeStaticText[@name=\"Choose\"]")).Click();
            driver.Context = driver.Contexts[1];
            Console.WriteLine(driver.Title);
            driver.FindElement(By.XPath("//input[@type='submit']")).Click();
            driver.Quit();
        }
```
