### ISSUE TITLE
autoAcceptAlerts cpability does not seems working in dotnet

### ISSUE THREAD

**Issue by smrtyviks** [appium/dotnet-client#489]
## Description
autoAcceptAlerts cpability does not seems working in dotnet

I am trying to automate my iOS App and when the App is launched the first time a popup message is displayed to accept that the app will be using the camera option with OK and Cancel button. I have tried this in Java framework the alert is managed by setting the "autoAcceptAlerts" capability. But with dotnet it does not seems to be working.
I have also tried using the below mentioned code but no luck.

_driver.SwitchTo().Alert().Accept();

## Environment

* .NET client build version or git revision if you use some shapshot: dotnet core 3.5
* Appium server version or git revision if you use some shapshot: Appium Webdriver 4.3.1
* Desktop OS/version used to run Appium if necessary: Macos
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 14.17.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

          var driverOption = new AppiumOptions();
                driverOption.AddAdditionalCapability(MobileCapabilityType.PlatformName, "iOS");
                driverOption.AddAdditionalCapability(MobileCapabilityType.DeviceName, "iPhone");
                driverOption.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, "15.2");

                driverOption.AddAdditionalCapability(MobileCapabilityType.App, appPath);
                driverOption.AddAdditionalCapability("autoAcceptAlerts", "true");

## Exception stacktraces

{\rtf1\ansi\ansicpg1252\cocoartf2636
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red200\green20\blue201;\red192\green192\blue192;
\red159\green160\blue28;\red111\green111\blue111;}
{\*\expandedcolortbl;;\csgray\c0;\cssrgb\c83397\c23074\c82666;\cssrgb\c79890\c79890\c79890;
\cssrgb\c68469\c68012\c14211;\cssrgb\c51167\c51167\c51167;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \CocoaLigature0 [debug] \cf3 [XCUITest]\cf2  Executing command 'getAlertText'\
[debug] \cf3 [WD Proxy]\cf2  Matched '/alert/text' to command name 'getAlertText'\
[debug] \cf3 [WD Proxy]\cf2  Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/2A8493E7-71C7-459F-A1D4-B5B399F30F2A/alert/text] with no body\
\cf3 [WD Proxy]\cf2  Got response with status 404: \{"value":\{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""\},"sessionId":"2A8493E7-71C7-459F-A1D4-B5B399F30F2A"\}\
[debug] \cf3 [W3C]\cf2  Matched W3C error code 'no such alert' to NoSuchAlertError\
[debug] \cf3 [W3C (8aca9491)]\cf2  Encountered internal error running command: NoSuchAlertError: An attempt was made to operate on a modal dialog when one was not open\
[debug] \cf3 [W3C (8aca9491)]\cf2      at errorFromW3CJsonCode (/Users/dkviksar/.nvm/versions/node/v14.17.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)\
[debug] \cf3 [W3C (8aca9491)]\cf2      at ProxyRequestError.getActualError (/Users/dkviksar/.nvm/versions/node/v14.17.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)\
[debug] \cf3 [W3C (8aca9491)]\cf2      at JWProxy.command (/Users/dkviksar/.nvm/versions/node/v14.17.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:272:19)\
[debug] \cf3 [W3C (8aca9491)]\cf2      at runMicrotasks (<anonymous>)\
[debug] \cf3 [W3C (8aca9491)]\cf2      at processTicksAndRejections (internal/process/task_queues.js:95:5)\
[debug] \cf3 [W3C (8aca9491)]\cf2      at XCUITestDriver.proxyCommand (/Users/dkviksar/.nvm/versions/node/v14.17.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)\
[debug] \cf3 [W3C (8aca9491)]\cf2      at XCUITestDriver.getAlertText (/Users/dkviksar/.nvm/versions/node/v14.17.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/alert.js:12:10)\
\cf3 [HTTP]\cf2  \cf4 <-- GET /wd/hub/session/8aca9491-c0e3-4c61-ad0b-c3fa308f54d1/alert/text \cf5 404\cf2  \cf6 77 ms - 1171\cf2 \
\cf3 [HTTP]\cf2  \
\
}

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by Dor-bl** [comment]
@akinsolb do you have the capacity to take a look at this from iOS side?
I'll try to check Android side

**Comment by Dor-bl** [comment]
@smrtyviks, I saw you are using an old version of the Appium Webdriver (4.3.1).
Can you please try the latest release? preferable with the beta one.

**Comment by Dor-bl** [comment]
Closed as no response since May.
