### ISSUE TITLE
I am unable to use openNotifications with Appium Driver

### ISSUE THREAD

**Issue by aaronportier** [appium/dotnet-client#497]
## Description

I am unable to get the Driver to work with openNotifications. It will work with Python.
does not contain a definition for openNotification and no accessible extension method
I am using C# I am using the Appium Nugget Package most recent via Visual Studio

## Environment

* Real device 
## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

_driver.openNotification()

**Comment by Dor-bl** [comment]
@aaronportier I assume you are referring to Android Driver. if that's the case you should try using OpenNotifications().
Are you using the [v5.0.0-beta01](https://github.com/appium/appium-dotnet-driver/releases/tag/v5.0.0-beta01) Package?
@akinsolb I think we should add an Integration test for that action.

**Comment by aaronportier** [comment]
I'm using the latest stable. Open notifications does not seem to work
though.

**Comment by Dor-bl** [comment]
It just won't work or you can't find a matching method?
Did you tried with the release version I sent?

**Comment by aaronportier** [comment]
I will try tomorrow for the now I just pull down the shade by coordinates
but open notifications is not usable and Open notifications does not do
anything.

**Comment by akinsolb** [comment]
@aaronportier @Dor-bl This feature is only [supported on emulators only.](https://appium.io/docs/en/commands/device/system/open-notifications/index.html)

**Comment by Dor-bl** [comment]
So I think we can close this issue. Unless something we can do on the .NET side in order to support as Python does.
@mykola-mokhnach any Input?

**Comment by akinsolb** [comment]
This works for physical devices on python client? @KazuCocoa is there a secret?

**Comment by KazuCocoa** [comment]
The endpoint calls https://developer.android.com/reference/androidx/test/uiautomator/UiDevice#opennotification , so the behavior depends on Android OS internals. Maybe .net client has the endpoint call https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/AppiumCommand.cs#L69 ...?

Python client also just calls the endpoint: https://github.com/appium/python-client/blob/ce4de83b443b050e295c5c1af0938ce720198bc8/appium/webdriver/extensions/android/common.py#L43-L50

**Comment by Dor-bl** [comment]
@akinsolb @aaronportier just tested it on my device and it worked just fine. added a test for it as well along the way

**Comment by Dor-bl** [comment]
Closed as unreproducible.
