### ISSUE TITLE
bug: ServerOptions.Arguments are not added to AppiumServiceBuilder args 

### ISSUE THREAD

**Issue by Dor-bl** [appium/dotnet-client#532]
## Description

Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium .NET client so please describe necessity of this feature and the way that it should work.

## Environment

* .NET client build version or git revision if you use some shapshot: [v5.0.0-beta01](https://github.com/appium/appium-dotnet-driver/releases/tag/v5.0.0-beta01)
* Appium server version or git revision if you use some shapshot: 2.0.0-beta.46
* Desktop OS/version used to run Appium if necessary: Win Home
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 16.18
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Not relevant

## Details

When adding caps to the server using OptionCollector, they are not added to the arguments list but the Options.
therefore, when AppiumServiceBuilder tries to add the caps as Arguments to the server arguments it's not been added, since the arguments list is empty on the serverOptions.
```
                if (ServerOptions != null)
                {
                    argList.AddRange(ServerOptions.Arguments);
                }
```

## Code To Reproduce Issue [ Good To Have ]

Run/Debug StartingAndroidAppWithCapabilitiesOnTheServerSideTest 

## Exception stacktraces

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by .NET.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by Dor-bl** [comment]
@akinsolb this is the issue we discussed on Slack.
I've opened this issue, so we can track it.

**Comment by Dor-bl** [comment]
Not a bug after all.
need to add `appium:automationName` to the client when starting a session with appium service builder and client caps
it's not enough to have `appium:automationName` only on server options.
@mykola-mokhnach / @jlipps  please confirm

**Comment by jlipps** [comment]
That's correct. automationName is a session capability, not related to the server.
