### ISSUE TITLE
[5.x] AppiumDriver has no implementation IFindsByImage<W> interface

### ISSUE THREAD

**Issue by dmitalexandrov** [appium/dotnet-client#551]
Master branch of AppiumDriver class contains an implementation of IFindsByImage<W>:
       #region IFindsByImage Members

        public W FindElementByImage(string base64Template) => FindElement(MobileSelector.Image, base64Template);

        public IReadOnlyCollection<W> FindElementsByImage(string base64Template) =>
            ConvertToExtendedWebElementCollection<W>(FindElements(MobileSelector.Image, base64Template));

        #endregion

But beta verions 5.0.0-beta02 has no methods for find element by image. 
Will this functionality move to 5.0.0 version?

**Comment by Dor-bl** [comment]
Those Members were removed as part of: https://github.com/appium/appium-dotnet-driver/pull/470

did you try the following instead? 
`_driver.FindElement(MobileBy.Image("Hello"));`

**Comment by dmitalexandrov** [comment]
Sure, but it returns IWebElement instead of ImageElement, and I have no access to specific properties like GetAttrubute(“visual”) for debug.

**Comment by Dor-bl** [comment]
And I assume performing casting on that object don't work either

**Comment by dmitalexandrov** [comment]
Are there any other ways to debug working with images?

**Comment by Dor-bl** [comment]
To be honest, I haven't worked with images yet. so I can't give you a good answer.
Maybe @akinsolb is more familiar with that

**Comment by dmitalexandrov** [comment]
> To be honest, I haven't worked with images yet. so I can't give you a good answer. Maybe @akinsolb is more familiar with that

Thanks for your replies, I just try to understand how can I debug using images as selector in 5.x version, because at thus moment test click in incorrect place in application.

**Comment by akinsolb** [comment]
@dmitalexandrov in order to "debug", or get attributes, I believe you would have to cast the return object to AppiumElement.

**Comment by Dor-bl** [comment]
@dmitalexandrov any updates on this issue? were you able to overcome the other issues you mentioned?

**Comment by jlipps** [comment]
@dmitalexandrov did you see that image finding is no longer part of appium itself? it's now supported by a plugin.

**Comment by Dor-bl** [comment]
Closed as no response.
