### ISSUE TITLE
[Feat]: Deprecate legacy app management helpers

### ISSUE THREAD

**Issue by Dor-bl** [appium/dotnet-client#562]
refer to: https://github.com/appium/java-client/pull/1571

**Comment by Dor-bl** [comment]
@mykola-mokhnach , we need to implement this, right?

**Comment by mykola-mokhnach** [comment]
right, this set of APIs will be eventuallyremoved from the server

**Comment by Dor-bl** [comment]
@mykola-mokhnach  can we close this or should I wait for https://github.com/appium/appium/issues/15807 to be closed?

**Comment by KazuCocoa** [comment]
Should be ok, thank you
