### ISSUE TITLE
[?] Running with .NET Framework 4.7.2 instead of 4.8

### ISSUE THREAD

**Issue by RoP09** [appium/dotnet-client#563]
Hello!

Due to some restrictions I cannot use .NET 4.8  for Appium 2.x  and the dotnet-client 5 beta in my environment. Is it possible to compile instead using .NET 4.7.2?

Thanks !

**Comment by akinsolb** [comment]
I'll get a patch out by the end of the week. This patch will include support for lowest possible target framework (including 4.72)

**Comment by RoP09** [comment]
Thanks! Got it running already on 4.7.2 now

**Comment by Dor-bl** [comment]
@RoP09 so we can close this issue?
