### ISSUE TITLE
[Bug?]: ScreenRecording not working with v2

### ISSUE THREAD

**Issue by RoP09** [appium/dotnet-client#564]
## Description
Executing:
iOSdriver.StartRecordingScreen(); 

## Environment
* .NET client 4.7.2
* Appium v2@next (latest)
* XCUITest
* MacOS 12.5
* iOS 15.4.2

## Details
Same setup / phone was working fine on Appium 1.22.3, after updating to v2 beta the screen never shows up on the client on the given ip address and port 9100. 
T(he connection is somehow established and streaming is started it seems (see log below) nevertheless, just nothing showing on the stream when I enter the address in the browser of the client.

# Log
`Calling AppiumDriver.startRecordingScreen() with args: [null,"6ca99db8-871c-44c1-8f0e-6fa526200fcc"]
[debug] [XCUITestDriver@8771 (6ca99db8)] Executing command 'startRecordingScreen'
[XCUITestDriver@8771 (6ca99db8)] Checking if there is/was a previous screen recording. Set 'forceRestart' option to 'true' if you'd like to skip this step.
[XCUITestDriver@8771 (6ca99db8)] Screen recording is not running. There is nothing to stop.
[DevCon Factory] Releasing connections for 00008101-00166D9026F9001E device on 9100 port number
[DevCon Factory] No cached connections have been found
[debug] [XCUITestDriver@8771 (6ca99db8)] Matched '/appium/settings' to command name 'getSettings'
[debug] [XCUITestDriver@8771 (6ca99db8)] Proxying [GET /appium/settings] to [GET http://127.0.0.1:8100/session/581866F2-7C00-4EEB-A8D8-F103FF56DFE8/appium/settings] with no body
[debug] [XCUITestDriver@8771 (6ca99db8)] Got response with status 200: {"value":{"boundElementsByIndex":false,"mjpegServerFramerate":10,"screenshotOrientation":"auto","reduceMotion":false,"elementResponseAttributes":"type,label","screenshotQuality":1,"mjpegScalingFactor":100,"keyboardPrediction":0,"defaultActiveApplication":"auto","mjpegServerScreenshotQuality":25,"defaultAlertAction":"","keyboardAutocorrection":0,"useFirstMatch":false,"shouldUseCompactResponses":true,"customSnapshotTimeout":15,"dismissAlertButtonSelector":"","activeAppDetectionPoint":"64.00,64.00","snapshotMaxDepth":50,"waitForIdleTimeout":10,"includeNonModalElements":false,"acceptAlertButtonSelector":"","animationCoolOffTimeout":2},"sessionId":"581866F2-7C00-4EEB-A8D8-F103FF56DFE8"}
[DevCon Factory] Requesting connection for device 00008101-00166D9026F9001E on local port 9100, device port 9100
[debug] [DevCon Factory] Cached connections count: 1
[DevCon Factory] Successfully requested the connection for 00008101-00166D9026F9001E:9100
[ffmpeg] ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
[ffmpeg]   built with Apple clang version 14.0.0 (clang-1400.0.29.102)
[ffmpeg]   configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
[ffmpeg] 
[ffmpeg]   libavutil      57. 28.100 / 57. 28.100
[ffmpeg]   libavcodec     59. 37.100 / 59. 37.100
[ffmpeg]   libavformat    59. 27.100 / 59. 27.100
[ffmpeg]   libavdevice    59.  7.100 / 59.  7.100
[ffmpeg] 
[ffmpeg]   libavfilter     8. 44.100 /  8. 44.100
[ffmpeg]   libswscale      6.  7.100 /  6.  7.100
[ffmpeg]   libswresample   4.  7.100 /  4.  7.100
[ffmpeg]   libpostproc    56.  6.100 / 56.  6.100
[ffmpeg] 
[ffmpeg] Input #0, mjpeg, from 'http://127.0.0.1:9100':
[ffmpeg]   Duration: N/A, bitrate: N/A
[ffmpeg] 
[ffmpeg]   Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1170x2532 [SAR 72:72 DAR 195:422], 25 tbr, 1200k tbn
[ffmpeg] 
[ffmpeg] Stream mapping:
[ffmpeg]   Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
[ffmpeg] Press [q] to stop, [?] for help
[ffmpeg] 
[ffmpeg] Output #0, mp4, to '/var/folders/8q/xjsd57ds7s77g1jzcmqvsv400000gn/T/2022112-38362-cguyr6.oql07/appium_77471d.mp4':
[ffmpeg]   Metadata:
[ffmpeg]     encoder         : Lavf59.27.100
[ffmpeg] 
[ffmpeg]   Stream #0:0: Video: mjpeg (mp4v / 0x7634706D), yuvj420p(pc, bt470bg/unknown/unknown, progressive), 1170x2532 [SAR 72:72 DAR 195:422], q=2-31, 200 kb/s, 25 fps, 12800 tbn
[ffmpeg]     Metadata:
[ffmpeg]       encoder         : Lavc59.37.100 mjpeg
[ffmpeg]     Side data:
[ffmpeg]       cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
[ffmpeg] 
[XCUITestDriver@8771 (6ca99db8)] Starting screen capture on the device '00008101-00166D9026F9001E' with command: 'ffmpeg -f mjpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 181 -i http://127.0.0.1:9100 -vcodec mjpeg -y /var/folders/8q/xjsd57ds7s77g1jzcmqvsv400000gn/T/2022112-38362-cguyr6.oql07/appium_77471d.mp4'. Will timeout in 180000ms
[debug] [XCUITestDriver@8771 (6ca99db8)] Responding to client with driver.startRecordingScreen() result: ""
[HTTP] <-- POST /session/6ca99db8-871c-44c1-8f0e-6fa526200fcc/appium/start_recording_screen 200 923 ms - 12
[HTTP] 
[HTTP] --> GET /session/6ca99db8-871c-44c1-8f0e-6fa526200fcc/window/rect
[HTTP] {}
[debug] [XCUITestDriver@8771 (6ca99db8)] Calling AppiumDriver.getWindowRect() with args: ["6ca99db8-871c-44c1-8f0e-6fa526200fcc"]
[debug] [XCUITestDriver@8771 (6ca99db8)] Executing command 'getWindowRect'
[debug] [XCUITestDriver@8771 (6ca99db8)] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/581866F2-7C00-4EEB-A8D8-F103FF56DFE8/window/size] with no body
[debug] [XCUITestDriver@8771 (6ca99db8)] Got response with status 200: {"value":{"width":390,"height":844},"sessionId":"581866F2-7C00-4EEB-A8D8-F103FF56DFE8"}
[debug] [XCUITestDriver@8771 (6ca99db8)] Responding to client with driver.getWindowRect() result: {"width":390,"height":844,"x":0,"y":0}
[HTTP] <-- GET /session/6ca99db8-871c-44c1-8f0e-6fa526200fcc/window/rect 200 110 ms - 48
[HTTP] 
[HTTP] --> GET /session/6ca99db8-871c-44c1-8f0e-6fa526200fcc/window/rect
`

**Comment by Dor-bl** [comment]
If this worked before appium server 2.x, then it sound like an issue you should report on the appium repo.

**Comment by RoP09** [comment]
ok got it running finally after finding out the the server start was wrong, used
 appium -p 9000
then changed that to the one given in the migration manual
 appium -p 9000 -a 127.0.0.1 -pa /wd/hub
but finally it it only works with
 appium server -p 9000 -a **0.0.0.0** -pa /wd/hub

**Comment by Dor-bl** [comment]
Great, closing as completed
