### ISSUE TITLE
[Bug]: AppiumElement.FindElement returns an IWebElement instead of an AppiumElement.

### ISSUE THREAD

**Issue by askariya** [appium/dotnet-client#573]
## Description
When I use the AppiumDriver.FindElement function, it returns an AppiumElement.
However, if I try to call FindElement on the AppiumElement itself (to find a nested element), then it returns an IWebElement instead (because it's using the WebElement base class implementation)

## Environment

* .NET client build version or git revision if you use some snapshot: 5.00-beta2 
* Appium server version or git revision if you use some snapshot: 2.0.0-beta.48
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 
* Mobile platform/version under test: Android OS 12
* Real device or emulator/simulator: Real Device

## Details

See Description above. I'm not 100% sure if this scenario is actually an error situation, but it seems incorrect to me and it requires a bit of working around in my code as a result. In v4.4.0, AppiumWebElement.FindElementByAccessibilityId() would return an AppiumWebElement not an IWebElement.
I'm questioning whether I should even be using AppiumDriver and not WebDriver instead? I was hoping using AppiumDriver would allow me to leave my code largely unchanged between Android, iOS and UWP testing while also restricting the available functions to ones that make sense for mobile testing.

## Code To Reproduce Issue [ Good To Have ]

Pseudo code below...
`AppiumDriver _driver = new AppiumDriver();
AppiumElement x = _driver.FindElement(MobileBy.AccessibilityId('SomeId'));
IWebElement y = x.FindElement(MobileBy.AccessibilityId('SomeOtherId')); // why not have a FindElement that returns AppiumElement instead?`

**Comment by Dor-bl** [comment]
@askariya please refer to https://github.com/appium/dotnet-client/issues/188 .
this workaround might work for you in the meantime. I'll try to find some time to take a look on it.

**Comment by dragojs** [comment]
Ran into this same issue while trying to move to the latest client rc1.
Is there any plans to have a fix for this?
I see @laolubenson has a commit somewhere with a fix(?) for this mentioned in issue #188. Is that not suitable?

**Comment by Dor-bl** [comment]
Not really, since @laolubenson commit contains type parameter for the appiumdriver, which was deprecated when we migrated to selenium 4.
I'll try to have a look on this issue myself, so if you can provide a sample code, it will will help me repro more easily .

**Comment by dragojs** [comment]
I am doing roughly something like this:
` 
Driver = new AndroidDriver(AppiumServer.ServerUri, options, AppiumDriverStartupTimeout);
IList<AppiumElement> myDerivedElements = default;
var myElement = Driver.FindElement(By.Id("some_locator"));
myDerivedElements = myElement.FindElements(By.Id("some_derived_locator"))
`
Visual Studio is recommending me to add an explicit cast for myDerivedElements (IList<AppiumElement>) to appease FindElements which is returning ReadOnlyCollection<IWebElement>.
I do this, but at runtime this conversion fails.
I could give the "as" cast a try in the meantime, I think that one at least won't fire an InvalidCastException, or I might try to use some XPaths instead but.. it'd be a bit dirty.

**Comment by dragojs** [comment]
@Dor-bl I haven't had the chance to try other selectors, I suspect it happens for others too, I edited my code comment again to be more specific.
I find an element By Id, then I use that element.FindElements(By.Xpath(...)) which gives me ReadOnlyCollection<IWebElement>s

**Comment by Dor-bl** [comment]
handled under https://github.com/appium/dotnet-client/pull/639
