### ISSUE TITLE
feat: add the ability to activate the app with timeout

### ISSUE THREAD

**Issue by laolubenson** [appium/dotnet-client#577]
**Is your feature request related to a problem? Please describe.**
The version 5 beta is missing the ability to activate the app with a timeout.

**Describe the solution you'd like**
Add the overload to the Driver.ActivateApp function like so in v4 #570

**Comment by Dor-bl** [comment]
@agentran feel free to raise a PR for v5	as well. Thanks!

**Comment by Dor-bl** [comment]
Merged
