### ISSUE TITLE
[Bug]: Cannot connect to appium server V1

### ISSUE THREAD

**Issue by Filjo0** [appium/dotnet-client#585]
## Description

After AppiumWebDriver (DotNet) update from 5.0.0-beta01 to 5.0.0-beta02 or 5.0.0-beta03 it's not possible to connect to AppiumServer.

## Environment

* Appium server version: 1.22.3:
* Real device:

## Configuration

                var capabilities = new AppiumOptions();
                capabilities.AddAdditionalAppiumOption(MobileCapabilityType.PlatformName, "Android");
                capabilities.AddAdditionalAppiumOption(AndroidMobileCapabilityType.AppActivity, "MainActivity");

                var appiumServer = new AppiumServiceBuilder().UsingAnyFreePort().Build();
                appiumServer.Start();

                var driver = new AndroidDriver(appiumServer, capabilities);

## Stacktrace:

The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: "C:\Users\...v\AppData\Roaming\npm\node_modules\appium\build\lib\main.js" --port "60870" --address "127.0.0.1". 

## Additional information

Adding an argument and hardcoding the port seems to help finding the server, but there's still an issue connecting to it.
var arguments = new OptionCollector().AddArguments(GeneralOptionList.BasePath("/wd/hub"));
var appiumServer = new AppiumServiceBuilder().UsingPort(4723).WithArguments(arguments).Build();

The error: 
[HTTP] No route found for /session
[HTTP] <-- POST /session 404 7 ms - 211
[HTTP]

**Comment by Dor-bl** [comment]
@Filjo0 please refer to : https://github.com/appium/dotnet-client/pull/587

**Comment by Filjo0** [comment]
> @Filjo0 please refer to: #587

Please refer to 'Additional information'.
Adding an argument '/wd/hub/' does not help.

**Comment by Dor-bl** [comment]
Sorry missed that part.
So it's most likely related to this bug :
https://github.com/appium/dotnet-client/issues/532

**Comment by Dor-bl** [comment]
@Filjo0 I ran a couple of tests from my side, and all works fine when adding the /wd/hub argument.
var args = new OptionCollector().AddArguments(GeneralOptionList.BasePath("/wd/hub"));

the reason it's not working for you could be that you are using appium 1.x Server, please try to update to appium 2.x

![image](https://user-images.githubusercontent.com/59066376/227463310-f8ae3a22-9e8b-4b0f-a0c6-fade87a68b6e.png)

**Comment by Filjo0** [comment]
> 

Well, in our case it's working fine using 5.0.0-beta01 and is broken using 5.0.0-beta02.

Also, Appium cannot be updated to 2.x due to certain reasons.

**Comment by Dor-bl** [comment]
I will try to have another look somewhere next week. But it might be problematic for me to repro the issue, since I'm using appium 2

**Comment by Dor-bl** [comment]
@Filjo0, Good news for you.  
Indeed there seems to be a bug on the appiumServiceBuilder when not passing the /wd/hub Option. related to: https://github.com/appium/dotnet-client/pull/529
i'll need to see if it's worth the effort to add a fix to appium V1 considering it's about to be Obsolete and users can still use the  
`var arguments = new OptionCollector().AddArguments(GeneralOptionList.BasePath("/wd/hub"));`

On the other end, using this Code does work for me so try to see what's wrong on your side:
``
var arguments = new OptionCollector().AddArguments(GeneralOptionList.BasePath("/wd/hub"));
var appiumServer = new AppiumServiceBuilder().UsingPort(4723).WithArguments(arguments).Build();
``

**Comment by Dor-bl** [comment]
@Filjo0 Appium 2 was officially released, are you still using appium 1?

**Comment by Dor-bl** [comment]
Closed as no response and since Appium server V1 is not supported any more
