### ISSUE TITLE
[Bug]: AppiumLocalService.Ping() uses LocalHost address - windows 10 proxy settings can cause Start() to report 503 error

### ISSUE THREAD

**Issue by aw2003** [appium/dotnet-client#596]
## Description

While working on an existing .Net project to test Android devices, I did some install rework on the rig, accidentally leaving proxies defined (http_proxy / https_proxy) in system environment vars. Rig is running Windows 10 20H2 19402.508 (admittedly old)

Ping() is run from Start() to confirm server availability, but if the default server IP address is used (127.0.0.1, AppiumServiceConstants.DefaultLocalIPAddress), Ping actually attempts http to "LocalHost":

        private bool Ping(TimeSpan span)
        {
            bool pinged = false;

            Uri status;

            Uri service = ServiceUrl;
            if (service.IsLoopback || IP.ToString().Equals(AppiumServiceConstants.DefaultLocalIPAddress))
            {
                status = new Uri("http://localhost:" + Convert.ToString(Port) + "/wd/hub/status");
            }
            else
            {
                status = new Uri(service.ToString() + "/status");
            }

The proxy settings for our squid server then meant this was sent to the proxy (established via debugging internally in HttpWebRequest) which returns 503. The server initialisation then times out.

Is there a reason Localhost is used, rather than 127.0.0.1? Manual use of 127.0.0.1 with the same URI returns the status correctly while the proxies are in place.

## Environment

* .NET client build version or git revision if you use some snapshot: Appium.WebDriver 4.4.0
* Appium server version or git revision if you use some snapshot: v1.22.3
* Desktop OS/version used to run Appium if necessary: Windows 10 20H2 19402.508
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v18.13.0
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device

## Details

All details above

## Code To Reproduce Issue [ Good To Have ]

```
               args.AddArguments(new KeyValuePair<string, string>("--relaxed-security", ""));
                args.AddArguments(new KeyValuePair<string, string>("--session-override", ""));
               // Start the appium service on the supplied port
                _appiumLocalService = new AppiumServiceBuilder()
                    .WithArguments(args)
                    .UsingPort(SessionPort)
                    .Build();
                _appiumLocalService.Start();
```

## Exception stack traces

Not required, exception was a 503 error which eventually results in AppiumServerHasNotBeenStartedLocallyException with "Time {InitializationTimeout.TotalMilliseconds} ms for the service starting has been expired!"

## Link to Appium logs

Appium server logs looked normal - showed the server starting as usual - e.g.

2023-03-02 13:07:27:936 [Appium] Welcome to Appium v1.22.3
2023-03-02 13:07:27:938 [Appium] Non-default server args:
2023-03-02 13:07:27:938 [Appium]   address: 127.0.0.1
2023-03-02 13:07:27:938 [Appium]   port: 4725
2023-03-02 13:07:27:939 [Appium]   sessionOverride: true
2023-03-02 13:07:27:939 [Appium]   logFile: C:\Windows\Temp\!Terminal 1_appium_server_log.log
2023-03-02 13:07:27:939 [Appium]   relaxedSecurityEnabled: true
2023-03-02 13:07:27:968 [Appium] Appium REST http interface listener started on 127.0.0.1:4725

**Comment by Dor-bl** [comment]
Which appium dotnet client version are you using?

**Comment by aw2003** [comment]
Updated description - apologies for missing that out, Package is Appium.WebDriver 4.4.0

**Comment by Dor-bl** [comment]
Hi.
Please try with appium beta version 5.x.
We no longer maintain version 4.

**Comment by aw2003** [comment]
Ping() source is unchanged in 5.x (checked https://github.com/appium/dotnet-client/blob/master/src/Appium.Net/Appium/Service/AppiumLocalService.cs) so issue will persist.

**Comment by Dor-bl** [comment]
you are looking in the wrong place.
this is the code for 5.x 
https://github.com/appium/dotnet-client/blob/release/5.0.0/src/Appium.Net/Appium/Service/AppiumLocalService.cs

**Comment by aw2003** [comment]
Many thanks - I'll take a look. Is there a timeline for v5.x release, I see betas - I ask because I'm creating a production test environment, and prefer stable releases. I can see Ping() rework there, promising.

**Comment by Dor-bl** [comment]
Unfortunately no timeline.
I'm the main contributer currently and have very little capacity with my main job.
I try to reach as many issues as possible before I can release a stable version and get out of beta stages

**Comment by Dor-bl** [comment]
@aw2003 any updates?

**Comment by aw2003** [comment]
Unfortunately I can't use beta versions and don't have a dev environment I can spare to test this at the moment - if you want to close this out, please feel free to do so. I'll pick up the new version at some point in the future but right now it's all build-out.
