### ISSUE TITLE
AppiumOptions.PlatformVersion does not become available in driver.Capabilities (Appium 5 Beta 3)

### ISSUE THREAD

**Issue by FourTwoOmega** [appium/dotnet-client#598]
When I set up my `AppiumOptions` object, I set `AppiumOptions.PlatformVersion` because there is an operation I can only do in iOS 15 and later. When I go to retrieve the value with `driver.Capabilities.GetCapability("platformVersion")` it returns `null`.

When I examine the driver's list of capabilities (`driver.Capabilities.ToString()`), `platformName` is there, but `platformVersion` is not.

Is there another way to retrieve it, or is this something that needs to be implemented?

As a work-around, I'm setting a different option for it, and this works:
`appiumOptions.AddAdditionalAppiumOption("platformVersion2", appiumOptions.PlatformVersion);`

**Comment by Dor-bl** [comment]
@FourTwoOmega 
For me all works fine, using the below set-up. I'm able to get PlatformVersion from both appiumOptions and _driver.Capabilities

`var capabilities = new AppiumOptions();
            capabilities.DeviceName = "Android Emulator";
            capabilities.PlatformName = "Android";
            capabilities.AutomationName = "UiAutomator2";
            capabilities.App = string.Empty;
            capabilities.PlatformVersion = "11";
            capabilities.AddAdditionalAppiumOption(AndroidMobileCapabilityType.ChromeOptions, chromeOptions);
            capabilities.AddAdditionalAppiumOption(MobileCapabilityType.NewCommandTimeout, 24 * 60 * 60);
            capabilities.AddAdditionalAppiumOption("wdaStartupRetries", "7");
            capabilities.AddAdditionalAppiumOption("wdaStartupRetryInterval", "20000");
`

![image](https://user-images.githubusercontent.com/59066376/227467204-0e36192d-8270-4ea4-af2c-cde0fdddd399.png)

Maybe you can share more Info. like what Appium Server version you use.

**Comment by Dor-bl** [comment]
Closed as no response
