### ISSUE TITLE
[Feat]: Next beta release?

### ISSUE THREAD

**Issue by agentran** [appium/dotnet-client#601]
When is the next release for beta is scheduled?

**Comment by Dor-bl** [comment]
Currently there is no ETA unfortunately.
I have a big feature I'm still working on. once I'll merge it, I hope I will be able prepare a new release.

**Comment by Dor-bl** [comment]
@agentran, beta04 is live!
https://github.com/appium/dotnet-client/releases/tag/v5.0.0-beta04
