### ISSUE TITLE
[Bug]: c# cannot capture dropdownlist object.

### ISSUE THREAD

**Issue by luqirun9999** [appium/dotnet-client#604]
## Description

Please describe the issue. It may be a bug description. So then please briefly describe the steps that you were trying to perform and what happened instead.
If there is a feature you want to see added to the Appium .NET client so please describe the necessity of this feature and the way that it should work.

## Environment

* .NET client build version or git revision if you use some snapshot:
* Appium server version or git revision if you use some snapshot:
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test:
* Real device or emulator/simulator:

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce a bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using C# and sample apps.
Also, you can create a [gist](https://gist.github.com) with pasted C# code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Exception stack traces

Please create a [gist](https://gist.github.com) with the pasted stack trace of exceptions thrown by .NET.

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by Dor-bl** [comment]
@luqirun9999 what is the issue? Please fill the the template

**Comment by luqirun9999** [comment]
Description
I want to capture the dropdown list element on my iOS app but failed. I can capture other elements like tab or radio button but failed on dropdown list element.

Environment
.NET client build version is 4.8:
Appium server version is :Appium-Server-GUI-windows-1.22.3-4
Desktop OS/version used to run Appium if necessary Windows 10 Enterprise:
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v18.15.0
Mobile platform/version under test:16.3.1
Real device or emulator/simulator:
Details
Please provide more details, if necessary.

Code To Reproduce Issue [ Good To Have ]
I am using latest tidevice to connect my Windows PC to my iPad and run the test case on my Windows PC.

Most of the element can be captured by the latest version of this github code but failed on dropdownlist.
                 _iosOptions = Caps.GetIosCaps(Apps.Get("iosUICatalogApp"));
                _driver = new IOSDriver(
                    new Uri("http://127.0.0.1:8100/"),                    _iosOptions);
                _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
                _driver.FindElement(MobileBy.Id("General")).Click();
                _driver.FindElement(MobileBy.Id("Patient Tab Information")).Click();

Exception stack traces
'unable to find an element using 'id', value 'Patient Tab Information''
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in D:\dotnet-client-release-5.0.0\src\Appium.Net\Appium\AppiumDriver.cs:line 92
   at OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver.FindElement(String by, String value) in D:\dotnet-client-release-5.0.0\src\Appium.Net\Appium\AppiumDriver.cs:line 106
   at OpenQA.Selenium.Appium.MobileBy.FindElement(ISearchContext context) in D:\dotnet-client-release-5.0.0\src\Appium.Net\Appium\MobileBy.cs:line 47
   at OpenQA.Selenium.WebDriver.FindElement(By by)
   at OpenQA.Selenium.Appium.AppiumDriver.FindElement(By by) in D:\dotnet-client-release-5.0.0\src\Appium.Net\Appium\AppiumDriver.cs:line 101
   at Appium2.Form1..ctor() in C:\Users\z0033cab\source\repos\Appium2\Appium2\Form1.cs:line 40

Link to Appium logs
Please create a [gist](https://gist.github.com/) which is a paste of your full Appium logs, and link them here. Do not paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, always include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by Dor-bl** [comment]
@luqirun9999 can you please share the appium server logs?

**Comment by Dor-bl** [comment]
Closed as no response
