### ISSUE TITLE
[Bug]: Can't grab modal dialog(windows) and close it 

### ISSUE THREAD

**Issue by erhan355** [appium/dotnet-client#611]
## Description

![image](https://user-images.githubusercontent.com/14984675/235658962-69856af5-02e1-4dc3-95de-096860ca25b1.png)
![image](https://user-images.githubusercontent.com/14984675/235658995-b3bb4668-392a-4f06-9079-a78af24e98e0.png)
![image](https://user-images.githubusercontent.com/14984675/235659030-07c6d9c9-0390-45fa-95ab-ab74b77feb40.png)

Up to now ,

I tried to grab object with xpath provided by WinAppDriverUIRecorder

I tried to find by modal's class name

I tried to locate root element and send escape key.

I tried to find pane by name and also grab dialog by using WindowHandles 

## Environment

Windows 10 

.Net Framework 4.5.2

WinAppDriver v1.2.1

Appium.WebDriver 4.4.0

Selenium.WebDriver 3.141.0

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

On any windows desktop application that shows modal dialog(window)

## Exception stack traces

OpenQA.Selenium.WebDriverException: 'An element could not be located on the page using the given search parameters.

**Comment by Dor-bl** [comment]
@erhan355  as a starting point I suggest you update the below :
Appium WebDriver -> beta04
Selenium WebDriver - 4.x

I have another question for you: What Appium server do you use?
Basically WInAppDriver is not marinated by MS for a long time now

**Comment by erhan355** [comment]
> @erhan355 as a starting point I suggest you update the below : Appium WebDriver -> beta04 Selenium WebDriver - 4.x
> 
> I have another question for you: What Appium server do you use? Basically, WInAppDriver is not marinated by MS for a long time now

@Dor-bl I am using  WinAppDriver v1.2.1.I have updated to Appium 5.0.0-beta04 but code is not compiling.I have checked tests for new syntax but it seems tests are outdated.
![image](https://user-images.githubusercontent.com/14984675/235789181-cbda3916-eefc-429f-8849-529f5b09c6b9.png)

Instead of winappdriver, I tried to use appium server and got exception on screenshot

![image](https://user-images.githubusercontent.com/14984675/235790895-949d9224-d72f-4642-b09d-5e536f9f1d98.png)

**Comment by erhan355** [comment]
Update 
I made following changes now it works.By the way, Could you please share code samples that shows how to instantiate windows driver  with Appium 5.0.0-beta04. 
` _desktopSession.SwitchTo().Window(_desktopSession.WindowHandles[0]);

**Comment by Dor-bl** [comment]
You can check this example
https://github.com/appium/dotnet-client/blob/release/5.0.0/test/integration/Windows/ClickElementTest.cs

**Comment by Dor-bl** [comment]
@erhan355 Can I close this issue?Or you need further assistance on this issue?

**Comment by Dor-bl** [comment]
Closed as no response.
