### ISSUE TITLE
[Feat]:Reconnect the device when the server already exists at SessionID

### ISSUE THREAD

**Issue by WantSoftware** [appium/dotnet-client#612]
The current version is very good and I thank the publishing team
But I have a small suggestion to improve appium using dotnet library
When using Request to perform actions, it is easy to reconnect the device by just getting the SessionID
When using the library, when reconnecting the device, it has to be initialized from the beginning and it takes a lot of time to connect.
I hope your team will fix this soon

**Comment by Dor-bl** [comment]
Hi @WantSoftware , happy to see you like our recent version.
I'm not sure if I understand what you mean here. Do you want to be able to connect to an existing session?
Can you please share a piece of the code that refers to the reconnect scenario?

**Comment by Dor-bl** [comment]
Closed as no response
