### ISSUE TITLE
Need Info - Can we install and use latest version of selenium nuget packages 

### ISSUE THREAD

**Issue by kv-naveen** [appium/dotnet-client#613]
Can we install and use latest version of selenium related nuget packages that overrides the dependencies installed as part of Appium.WebDriver ? If Yes,
Are we sure that the Appium functionality works as expected even after this?
 Is it recommended?

**Comment by Dor-bl** [comment]
Can you please share the versions you are referring to?
Selenium and appium.
Basically if you would like to use selenium 4 you Will need to use Appium dotnet client 5.x

**Comment by kv-naveen** [comment]
@Dor-bl Thank you for the quick response.
I have a requirement to use both WinAppDriver and Selenium. 
I have installed latest version of appium nuget package ( 5.x beta) . This  installed  selenium webdriver  4.5.1 as a dependency . When I try to install latest selenium ( 4.9.1) nuget package it overrides the existing 4.5.1.
So just wanted to know if this causes some unexpected behavior on the Appium Side ? Or it is better to  just use selenium that is shipped with appium.

**Comment by Dor-bl** [comment]
It shouldn't.
Regardless , I need to find the time and update the selenium package inside of the appium dotnet client.

**Comment by Dor-bl** [comment]
Next release will incde latest selenium packages
https://github.com/appium/dotnet-client/pull/630
