### ISSUE TITLE
[Bug]: WinAppDriver shutting down after 60 seconds (newCommandTimeout is set as well as contructor with timeout)

### ISSUE THREAD

**Issue by ZigaJavornik** [appium/dotnet-client#616]
## Description

I know this is very similar to what is described in issue [224](https://github.com/appium/dotnet-client/issues/224). But please bear with me and try to point out if there is something I am missing...

When I do not interact with the driver for over 60 seconds, in my Appium logs, it is clear that the driver is deleted due to command timeout:
![image](https://github.com/appium/dotnet-client/assets/121696359/e0486d0f-9298-4823-8783-c1deafc76650)

## Environment

.net framework 4.8
Appium 1.22.3
Windows 10
Selenium.WebDriver 3.141.0

## Code To Reproduce Issue [ Good To Have ]

```
AppiumOptions options = new AppiumOptions();
options.AddAdditionalCapability("platformName", "Windows");
options.AddAdditionalCapability("deviceName", "WindowsPC");
options.AddAdditionalCapability("app", applicationPath);
options.AddAdditionalCapability("appArguments", arguments);
options.AddAdditionalCapability("ms:waitForAppLaunch", "10");
options.AddAdditionalCapability("fullReset", "true");
options.AddAdditionalCapability("newCommandTimeout", 600);

AppSession = new WindowsDriver<WindowsElement>(new Uri(driverUrl), options, TimeSpan.FromSeconds(600));
```

When the driver is being called it throws an exception that the driver is terminated or not started. I have only recently found this out, up until now my tests have lasted under 60 seconds, now that I have made a longer test, the next one fails since the driver is not called in the time of the test.

**Comment by ZigaJavornik** [comment]
It was my mistake, I had created another driver which I did not send the capability for timeout. I do have 2 questions though:
1. Is it necessary to use the "appium:" prefix setting the capability?
2. Is it true that I should create a new driver for every new window? I was told that for every window, I should create a new driver and delete it when the window is closed.

**Comment by Dor-bl** [comment]
Hi @ZigaJavornik

1.If you are using the beta version of the appium dotnet client you don't need to pass the appium: prefix since it's already added automatically.
2. Sounds right to me.
