### ISSUE TITLE
[Bug]: I need support from version 1.x to 2.x

### ISSUE THREAD

**Issue by JohnJS21** [appium/dotnet-client#620]
in version 1.x i can use below code to start appium server but when update to 2.x version it doesn't work i need to set up anything
AppiumLocalService appiumLocalService = new AppiumServiceBuilder()
                                                                       .WithIPAddress("127.0.0.1")
                                                                       .UsingPort(4723)
                                                                       .WithAppiumJS(new FileInfo("path main.s"))
                                                                       .WithLogFile(new FileInfo("logFile.txt"))
                                                                       .Build();
            appiumLocalService.Start();

**Comment by Dor-bl** [comment]
Hi @JohnJS21 can you please share the exception you are getting?
