### ISSUE TITLE
[Bug]: 'automationName' Can't Be Blank

### ISSUE THREAD

**Issue by wizzbangwa** [appium/dotnet-client#622]
## Description

Regardless of what I do, I cannot get passed "'automationName' Can't Be Blank".  I have been working for hours trying to get passed this problem since every library involved claims the problem is fixed, but nope, it's not.  I am at a complete stand still until properly fixed, or a bypass solution can be found.  If I understand the logs, dontnet-client library is where the problem lies.

## Environment

* .NET client build version or git revision if you use some snapshot: 5.0.0 Beta 4 (downloaded 5 times, latest 10 minutes ago)
* Appium server version or git revision if you use some snapshot: 2.0.0, installed using NPM
* Desktop OS/version used to run Appium if necessary:  Windows 10 Professional
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:  20.4.0
* Mobile platform/version under test:  N/A
* Real device or emulator/simulator:  Real device
* WebDriver and Webdriver.Support version 4.10.0

## Details

dotnet-client is self compiled using version 5.0.0 beta 4.  An already compiled version can't be found, so I compiled my own.  I could be compiling the wrong code, hence why I looked for an already compiled version.  Would be a good ide to provide a compiled download to avoid potential mistakes by someone trying to compile, especially when a nuget for a needed version isn't available.  GitHub Actions can easily take care of compiling and adding to the release/prerelease artifacts.

I can't find anything that shows how to properly use Appium along with this library, only old samples not yet updated.  Code is pieced together from old examples and errors I receive during runtime.

## Code To Reproduce Issue [ Good To Have ]

internal void CreateWebDriver(string windowhex)
        {
            if (string.IsNullOrEmpty(windowhex)) throw new ArgumentNullException(nameof(windowhex));

            AppiumOptions appCapabilities = new AppiumOptions();
            appCapabilities.AddAdditionalAppiumOption("AutomationName", "windows");
            appCapabilities.AddAdditionalAppiumOption("platformName", "Windows");
            appCapabilities.AddAdditionalAppiumOption("DeviceName", "WindowsPC");
            appCapabilities.AddAdditionalAppiumOption("appTopLevelWindow", windowhex);
        }

I also used the following lines trying to fix with no success:
appCapabilities.AddAdditionalAppiumOption("automationName", "windows");  - I get told to use "AutomationName" instead.
appCapabilities.AddAdditionalAppiumOption("appium:automationName", "windows"); - get told "appium:automationName" is already added.

## Exception stack traces

https://gist.github.com/wizzbangwa/58bc8655e944ca5cd6498662cc5d56de

## Link to Appium logs

Where are the logs located?  I can't find any useful information on this and your generated bug report helper doesn't say where to look.  

Below is what is shown in the command prompt window.
[Appium] Could not parse W3C capabilities: 'automationName' can't be blank
[debug] [AppiumDriver@63fa] Event 'newSessionStarted' logged at 1688715290630 (00:34:50 GMT-0700 (Pacific Daylight Time))
[debug] [AppiumDriver@63fa] Encountered internal error running command: InvalidArgumentError: 'automationName' can't be blank
[debug] [AppiumDriver@63fa]     at processCapabilities (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\capabilities.js:345:13)
[debug] [AppiumDriver@63fa]     at parseCapsForInnerDriver (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\lib\utils.js:139:40)
[debug] [AppiumDriver@63fa]     at AppiumDriver.createSession (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\lib\appium.js:251:49)
[debug] [AppiumDriver@63fa]     at commandExecutor (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:107:18)
[debug] [AppiumDriver@63fa]     at AppiumDriver.executeCommand (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:124:15)
[debug] [AppiumDriver@63fa]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@63fa]     at defaultBehavior (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\lib\appium.js:680:16)
[debug] [AppiumDriver@63fa]     at AppiumDriver.executeWrappedCommand (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\lib\appium.js:774:16)
[debug] [AppiumDriver@63fa]     at AppiumDriver.executeCommand (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\lib\appium.js:696:17)
[debug] [AppiumDriver@63fa]     at asyncHandler (C:\Users\blaze\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:393:19)

**Comment by Dor-bl** [comment]
@wizzbangwa Did you try the below code?
AppiumOptions desktopCapabilities = new AppiumOptions();
                    desktopCapabilities.App = "Root";
                    desktopCapabilities.DeviceName = "WindowsPC";
                    desktopCapabilities.AutomationName = "Windows";
                    var desktopSession = new WindowsDriver(serverUri, desktopCapabilities);

**Comment by wizzbangwa** [comment]
Thanks for the fast reply.  That got me going in the right direction, but I am still not up.  

First, I see the following in my command prompt output:
[WindowsDriver@012e] The following capabilities were provided, but are not recognized by Appium:
[WindowsDriver@012e]   deviceName

Appium and WebAppDriver are way too complicated to get going.  Right now I am stuck at Appium not being able to contact WebAppDriver.  I don't think WebAppDriver doesn't like providing statuses.  THis is in the log after WebAppDriver is started.
[WindowsDriver@012e (197d4e76)] Spawning 'C:\Program Files\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
[debug] [WindowsDriver@012e (197d4e76)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@012e (197d4e76)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@012e (197d4e76)] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
[debug] [WindowsDriver@012e (197d4e76)] Press ENTER to exit.
[debug] [WindowsDriver@012e (197d4e76)] ==========================================
[debug] [WindowsDriver@012e (197d4e76)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@012e (197d4e76)] Accept: application/json, */*
[debug] [WindowsDriver@012e (197d4e76)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@012e (197d4e76)] Connection: keep-alive
[debug] [WindowsDriver@012e (197d4e76)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@012e (197d4e76)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@012e (197d4e76)] User-Agent: appium
[WindowsDriver@012e (197d4e76)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError

Is this something I should report somewhere else?

**Comment by Dor-bl** [comment]
Did you used as followed? 
`desktopCapabilities.DeviceName = "WindowsPC";`

**Comment by wizzbangwa** [comment]
I sure did.
```
AppiumOptions desktopCapabilities = new AppiumOptions
{
     App = "Root",
     DeviceName = "WindowsPC",
     AutomationName = "Windows"
};
desktopCapabilities.AddAdditionalAppiumOption("appTopLevelWindow", windowhex);
_ticketNetworkSession = new WindowsDriver(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
```

**Comment by jlipps** [comment]
Looks like WinAppDriver threw an error. This isn't surprising as it hasn't been maintained for many years. Unfortunately the only solution might be to complain to Microsoft in order to help convince them to update WAD.

**Comment by Dor-bl** [comment]
@wizzbangwa, looks like you are trying to run on the Windows Application Driver which is not W3C compatible for a while now.
The only option you have currently is to run on the appium server using [Appium Windows Driver] a(https://github.com/appium/appium-windows-driver) which is used as a proxy to WinAppDriver.
I need to add a section for this on the Repo README.MD
See: 
https://github.com/appium/dotnet-client/issues/487

**Comment by wizzbangwa** [comment]
I found the problem: I was using both App and appTopLevelWindow.  Only one can be used.  Thanks for the suggestions and extra information.

I am looing into Appium Windows Driver.
