### ISSUE TITLE
[Maui]: Compatability

### ISSUE THREAD

**Issue by aaronportier** [appium/dotnet-client#663]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dor-bl** [comment]
@aaronportier, please describe the issue/ feature request

**Comment by aaronportier** [comment]
Sorry I wanted to know how well this works with Maui apps going from
Xamarin.

**Comment by Dor-bl** [comment]
@aaronportier, if it's not a real issue/ Feat request, please close

**Comment by aaronportier** [comment]
I thought asking about how it works with Maui could lead to specific
issues/Requests. I like Most people are moving from Xamarin and
understanding how well the 5.x nugget works with Maui seems relevant but if
you feel that's too broad you are welcome to close it out.
Thank you

**Comment by Dor-bl** [comment]
I'll close it since there is no actual and specific issue here.
If you came across anything, feel free to open a new issue.
Thank you
