### ISSUE TITLE
Context function not working 

### ISSUE THREAD

**Issue by MateuszC05** [appium/dotnet-client#668]
I open the theme again, I have to work on appium version 4.4.5, I can't switch between WebView and NativeView context, the cmd displays No route found for /wd/hub/session/{sesionID}/contexts. Please help. I noticed that in Appium inspector, switching between contexts works, but the POST that is sent looks like No route found for /wd/hub/session/{sesionID}/contexts

**Comment by Dor-bl** [comment]
As I said, 4.4.5 is out of support and no longer maintained. I suggest you migrate to v5.0

**Comment by MateuszC05** [comment]
we cannot currently migrate to the latest version, is there any other way to fix this? As for the new version, can you please send some migration instructions?

**Comment by MateuszC05** [comment]
this is my bug

**Comment by MateuszC05** [comment]
I managed to solve the problem by migrating the whole project to the latest version of appium 5, it took some time and created problems but it works, Thanks for your help
