### ISSUE TITLE
[Feat]: CDP!

### ISSUE THREAD

**Issue by DongMongppp** [appium/dotnet-client#689]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Will APPIUM support the CDP function supported by Selenium?

**Comment by Dor-bl** [comment]
@jlipps @mykola-mokhnach, is this a client thing or more related to server side?
Anayway I don't see a point putting the effort into it while selenium already mentioned they are favoring the BiDi protocol https://w3c.github.io/webdriver-bidi/
You can also read more about it here https://www.selenium.dev/documentation/webdriver/bidirectional/

**Comment by KazuCocoa** [comment]
`cdp` endpoint for HTTP request, I think this dotnet also should work. https://github.com/search?q=repo%3ASeleniumHQ%2Fselenium+executeCdp+language%3AC%23&type=code&l=C%23
it sends a cdp command, and appium proxies the request to the chromedriver.

Other driver does not support the cdp endpoint.

In terms of over websocket stuff, possibly https://github.com/appium/appium/pull/19404 ?
But I'm not sure if C# in selenium has the functionality to speak websocket.


https://github.com/mykola-mokhnach/appium-devtools-plugin may also be helpful if you're interested in attaching to devtools protocol.

**Comment by Dor-bl** [comment]
@DongMongppp did you tried https://github.com/mykola-mokhnach/appium-devtools-plugin?

**Comment by Dor-bl** [comment]
@DongMongppp, Let us know if the above is what you were looking for before I close this issue.

**Comment by Dor-bl** [comment]
Closed due to no response.

**Comment by Dor-bl** [comment]
Closed due to no response.
