### ISSUE TITLE
I am confused about how should I use WinAppDriver on .NET in the future

### ISSUE THREAD

**Issue by PeterHevesi** [appium/dotnet-client#711]
Because in your docs, it says I should use this fork:
https://github.com/appium/appium-windows-driver

But it is just all Javascript, installing via npm, but I would like to use WinAppDriver in my .NET 8 project :)
Is it possible? Or will it be possible in the future?

**Comment by Dor-bl** [comment]
Have you download the WAD from https://github.com/microsoft/WinAppDriver?

**Comment by PeterHevesi** [comment]
Yeah sure, I am already using it :) I use it with Appium.WebDriver 4.4.5, and it is working good, so I can just stay forever on this version, but I was curious, if is it some way to upgrade to Appium.WebDriver 5 and still using WinAppDriver with it in .NET 8 project?

**Comment by Dor-bl** [comment]
@PeterHevesi You can upgrade to Appium dotnet 5, and it's highly recommended. Just keep in mind you will probably have some issues with some of the actions since MS abandoned the WAD
you can read more about this on the following topic: https://github.com/appium/dotnet-client/issues/487.

**Comment by Dor-bl** [comment]
@PeterHevesi, Can I close this issue?

**Comment by PeterHevesi** [comment]
Yeah sure, you can close it, you showed me the other thread so I will try it when I have time. Thanks for your help :)
