### ISSUE TITLE
[Bug]: Creating WindowsDriver with AppiumOptions throws exeption 

### ISSUE THREAD

**Issue by Pegieo** [appium/dotnet-client#718]
## Description

Could not create WindowsDriver to start session with Windows applicaction. The code below throws exception: "OpenQA.Selenium.WebDriverArgumentException : Bad capabilities. Specify either app or appTopLevelWindow to create a session"

## Environment

Windows, Desktop
Appium.WebDriver" Version="5.0.0-rc.2"

## Details
It works with version 4.4.5

## Code To Reproduce Issue

```
var appiumOptions = new AppiumOptions
                    {
                        App = "Notepad.exe",
                        DeviceName = "WindowsPC",
                        PlatformName = "Windows"
                    };

var driver = new WindowsDriver(new Uri(WindowsApplicationDriverUrl), appiumOptions);

**Comment by Dor-bl** [comment]
Try to add 'automationName' capability as well

**Comment by Pegieo** [comment]
> Try to add 'automationName' capability as well

It still does not work.

**Comment by mykola-mokhnach** [comment]
If you are trying to use this client without Appium itself then it won't work as WAD does not support the W3C protocol.

**Comment by Pegieo** [comment]
But it worked with version 4.4.5 🤔

**Comment by Dor-bl** [comment]
Which appium version are you using?

**Comment by Pegieo** [comment]
WinAppDriver v1.2.1 but also tried v1.3

**Comment by Dor-bl** [comment]
I meant appium server driver

**Comment by Pegieo** [comment]
Yes, using Appium instread of WinAppDriver directly resolved that problem. 
However, I got stuck with other issues for now e.g. https://github.com/microsoft/WinAppDriver/issues/1886
Thanks for help!

**Comment by Dor-bl** [comment]
@Pegieo, Can I close this issue?
