### ISSUE TITLE
[Bug]: AppiumOptions.ToDictionary() returns an empty dictionary

### ISSUE THREAD

**Issue by s-glatshtein** [appium/dotnet-client#724]
## Description

trying to get options as a dictionary doesn't return any Appium values

## Environment

* Appium.NET 5.0.0-rc.4
* Appium 2.2.4

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

all I did was set some capabilities using `AddAdditionalAppiumOption` and then called `ToDictionary`

**Comment by Dor-bl** [comment]
@s-glatshtein, thank you for reporting the issue. A fix will be available on the next release.
