### ISSUE TITLE
[Feat]: 5.0 release

### ISSUE THREAD

**Issue by KazuCocoa** [appium/dotnet-client#726]
@Dor-bl @laolubenson do you think we can make the 5 RC.5 to stable release... (as no blocking known issues)?

**Comment by Dor-bl** [comment]
@KazuCocoa we have this bug which I prefer to fix before the stable release:
https://github.com/appium/dotnet-client/issues/724

**Comment by KazuCocoa** [comment]
I see. Thank you!

**Comment by Dor-bl** [comment]
@KazuCocoa I've just released V5 RC.5, if no new issues arise I assume the next version can be the stable one.
However, I think I first need to remove the obsolete methods we've been dragging for some time now, e.g. TouchAction, LaunchApp, ReplaceValue

**Comment by jamesmcroft** [comment]
Appium team, I have a question which could be a separate issue (happy to create if needs be) that I wanted to ask here around 5.0. 

With Selenium still supporting .NET Standard 2.0, was there a specific reason to move to .NET 6.0 with this library? Apologies if I have missed this.

**Comment by Dor-bl** [comment]
The primary reason for transitioning to .NET 6 was to enable the execution of this project on a new Mac machine. The compatibility between .NET Framework 4.8 and Visual Studio Code with the C# Dev Kit was proving to be problematic.

**Comment by Dor-bl** [comment]
@KazuCocoa, I hope rc.7 will be the latest RC version.
I still need to prepare a draft for the stable release of 5.x so it might take some time.

**Comment by mialeska** [comment]
@Dor-bl Could netstandard2.0 be restored as an additional target framework?
I can see there still are some properties in your csproj that use it in conditions:
![image](https://github.com/appium/dotnet-client/assets/9014926/359582c7-41da-41b6-82aa-3aad31315c99)
I am interested because in my case, I am supporting appium-wrapper library that uses netstandart2.0 as a target, to make it compatible to both .NET core and .NET Framework.

**Comment by Dor-bl** [comment]
@mialeska, I assume it can be done, I just need to run a few tests before.
@laolubenson, Do you see any downside with adding .NET Standard 2.0 back?

**Comment by Dor-bl** [comment]
https://github.com/appium/dotnet-client/releases/tag/v5.0.0 is now available.
Closing as completed.
