### ISSUE TITLE
Rotate throw System.NotImplementedException

### ISSUE THREAD

**Issue by ptittof57** [appium/dotnet-client#755]
## Description

Hello,

I try to perfom a device rotation with the following code:

```    
    [Test]
    public void RotationTest()
    {
        var rotation90Degrees = new Dictionary<string, int>
        {
            { "rotation", 90 },
        };

        this.Driver.Rotate(rotation90Degrees);

        Assert.IsTrue(this.Driver.Orientation == ScreenOrientation.Landscape);
    }
```  

But I receive an exception.

## Environment

* .NET client build version or git revision if you use some snapshot: Appium.WebDriver - 5.0.0-rc.6
* Appium server version or git revision if you use some snapshot: 2.4.1
* Desktop OS/version used to run Appium if necessary: MacOs Sonoma 14.3.1
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 20.11.1
* Mobile platform/version under test: Android (API28) and iOS (iPhone 15 Pro iOS 17.2)
* Real device or emulator/simulator: both Android and iOS simulators

## Exception stack traces

Exception has occurred: CLR/System.NotImplementedException
An exception of type 'System.NotImplementedException' occurred in WebDriver.dll but was not handled in user code: 'The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource'
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.Execute(String driverCommandToExecute, Dictionary2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.Rotate(Dictionary2 opts)
   at UITests.DashboardTest.RotationTest() 

Let me know if I am doing something wrong or if this feature is not implemented yet.
Thanks

**Comment by KazuCocoa** [comment]
Could you share the appium server log as well? I assume https://github.com/appium/dotnet-client/blob/23ae815afb74e51172b15dbc6a1558387ed021f8/src/Appium.Net/Appium/AppiumDriverCommand.cs#L289 would work for now

**Comment by Dor-bl** [comment]
@ptittof57 
This should do the trick
```
            _driver.Orientation = ScreenOrientation.Landscape;
            Assert.That(_driver.Orientation == ScreenOrientation.Landscape);
```
@KazuCocoa I deprecate the `rotate` method? what's the status of other appium clients?

**Comment by KazuCocoa** [comment]
The rotate does not have much usage, and it is not w3c. It is safe to remove it I think.
Python and Ruby clients do not have the rotation endpoint call. Java still has. They have the orientation endpoint call.

**Comment by Dor-bl** [comment]
@KazuCocoa Any idea what Rotate on Element is supposed to do?
Maybe it's a mistake
https://github.com/appium/dotnet-client/blob/main/src/Appium.Net/Appium/AppiumElement.cs#L199-L208

**Comment by KazuCocoa** [comment]
Perhaps it is for https://github.com/appium/appium/pull/19379 . The implementation did not exist on current drivers. Thus, I removed that endpoint.

**Comment by Dor-bl** [comment]
> Perhaps it is for [appium/appium#19379](https://github.com/appium/appium/pull/19379) . The implementation did not exist on current drivers. Thus, I removed that endpoint.

Great, so it's safe to remove this method as well and the related endpoint on our side

**Comment by mykola-mokhnach** [comment]
I'd say rotation could be implemented as an extension method. 
Also, to add on that:
- Orientation is limited. It only supports portrait and landscape, while rotation supports various angles (in reality for iOS and Android it add two more possible states)
- Rotation (and orientation) are not applicable for all drivers
