### ISSUE TITLE
Currently only pen and touch pointer input source types are supported

### ISSUE THREAD

**Issue by valinprogress** [appium/dotnet-client#764]
## Description

I have a winforms application. I am trying to automate the selection with a mouse in a System.Windows.Forms.ToolStripMenuItem. The dotnet client won't let me, maybe I'm making a mistake? Maybe someone already solved the issue if it is an issue?

## Environment

.NET 6 with C#
Appium server version 2.5.1
dotnet-client: Appium.WebDriver 5.0.0-beta02
Selenium.WebDriver 4.5.1
appium-windows-driver
OS Windows 11
npm 10.5.0
Windows Application

## Details

See the exception stack trace. I have slightly modified the sample code provided in the README.

## Code To Reproduce Issue [ Good To Have ]

```
var touch = new OpenQA.Selenium.Appium.Interactions.PointerInputDevice(PointerKind.Mouse, "WindowsPC");
var sequence = new ActionSequence(touch);
var move = touch.CreatePointerMove(elementToClick, elementToClick.Location.X, elementToClick.Location.Y, TimeSpan.FromSeconds(10));
var actionPress = touch.CreatePointerDown(MouseButton.Touch);
var pause = touch.CreatePause(TimeSpan.FromMilliseconds(250));
var actionRelease = touch.CreatePointerUp(MouseButton.Touch);

sequence.AddAction(move);
sequence.AddAction(actionPress);
sequence.AddAction(pause);
sequence.AddAction(actionRelease);

var actions_seq = new List<ActionSequence>
	{
		sequence
	};

driver.PerformActions(actions_seq);
```

## Exception stack traces

OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=Currently only pen and touch pointer input source types are supported
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.PerformActions(IList`1 actionSequenceList)

## Link to Appium logs

Available on request

**Comment by Dor-bl** [comment]
Related: https://github.com/microsoft/WinAppDriver/issues/1727
WinAppDriver is not supported by Microsoft for a long time now..

**Comment by Dor-bl** [comment]
@valinprogress, Can you try running the same code while using the driver below:
https://github.com/FlaUI/FlaUI.WebDriver

**Comment by valinprogress** [comment]
I am trying it. Re to the code in the documentation:

`using OpenQA.Selenium;

public class FlaUIDriverOptions : DriverOptions
{
    public static FlaUIDriverOptions App(string path)
    {
        var options = new FlaUIDriverOptions()
        {
            PlatformName = "windows"
        };
        options.AddAdditionalOption("appium:app", path);
        return options;
    }

    public override ICapabilities ToCapabilities()
    {
        return GenerateDesiredCapabilities(true);
    }
}

var driver = new RemoteWebDriver(new Uri("http://localhost:4723"), FlaUIDriverOptions.App("C:\\YourApp.exe"));`

How do I use the method "ToCapabilities()"? In WindowsDriver I have the option 

`capabilities.AddAdditionalAppiumOption("waitForAppLaunch", "25");`

that allows me to bypass the splash screen of my application, but in FlaUI.WebDriver I don't have this option hence the application crashes.

**Comment by Dor-bl** [comment]
Using `capabilities.AddAdditionalOption("waitForAppLaunch", "25");` doesn't work?

**Comment by valinprogress** [comment]
As per documentation, "waitForAppLaunch" is not supported by FlaUI.WebDriver

**Comment by Dor-bl** [comment]
You might want to open an issue on their end

**Comment by valinprogress** [comment]
Thanks @Dor-bl , I will consider to open an issue on FlaUI.WebDriver side

**Comment by Dor-bl** [comment]
@valinprogress, Can we close this issue since you are taking it with FlaUI?

**Comment by Dor-bl** [comment]
Closed due to no response.
