### ISSUE TITLE
PageFactory and ExpectedConditions are Obsolete.

### ISSUE THREAD

**Issue by gshuchi** [appium/dotnet-client#770]
Since, the above are obsolete. DotNetSeleniumExtras can be used. 
But the **DotNet Client's Wiki** for Appium has -
**PageFactory.InitElements(context, screenOrPage , new AppiumPageObjectMemberDecorator());** 
Now, here error comes that -"PageFactory does not exist in the current context."
I'm trying to automate an Native App which is present on **both Android & iOS Platforms.**
Then How can we define elements for both iOS & Android to execute them in **Parallel.** 
**Kindly update the DotNet Client Documentation with Latest Appium 2.x.x. examples in a more easy way** 
<img width="1023" alt="Screenshot 2024-04-08 at 18 56 23" src="https://github.com/appium/dotnet-client/assets/17813277/839799bb-94a4-4555-9bc7-247a4eca971b">

**Comment by Dor-bl** [comment]
@gshuchi, What appium dotnet client are you using?

**Comment by gshuchi** [comment]
Hey @Dor-bl. Thanks for checking this issue. Please find the Dependencies list of my project -
<img width="341" alt="Screenshot 2024-04-12 at 23 06 23" src="https://github.com/appium/dotnet-client/assets/17813277/0d2a7a1c-dadc-437c-af03-481f22c87231">

**Comment by Dor-bl** [comment]
You are using an out of support version of this client. I suggest you update to version 5.x. Thing is page objects is obsolete on that version. Maybe you can try and find another alternative.

**Comment by KazuCocoa** [comment]
Appium.WebDriver 4.4.5 should be v5 rc https://www.nuget.org/packages/Appium.WebDriver/absoluteLatest#versions-body-tab
https://github.com/appium/dotnet-client?tab=readme-ov-file#v5-release-candidate

**Comment by gshuchi** [comment]
@Dor-bl @KazuCocoa Thanks a ton!
