### ISSUE TITLE
[Chore]: Update Wiki page -How-to-start-an-AppiumDriver-locally

### ISSUE THREAD

**Issue by Dor-bl** [appium/dotnet-client#776]
## Description

The below Wiki page needs an update. (code is currently for version 4)
https://github.com/appium/dotnet-client/wiki/How-to-start-an-AppiumDriver-locally

**Comment by seriousQA** [comment]
@Dor-bl , thanks, now it works. I'll update the page..

**Comment by Dor-bl** [comment]
@seriousQA Just a reminder it needs to match the latest client version

**Comment by Dor-bl** [comment]
@seriousQA 
Thanks a lot for your work. much appreciated.
some comments:
1. The known issue section is empty. can be removed if no info can be added
2. the https://github.com/appium/dotnet-client/wiki/How-to-start-an-AppiumDriver-locally#how-to-create-an-androiddriver-instance part seems outdated: See https://github.com/appium/dotnet-client/blob/v4/src/Appium.Net/Appium/Android/AndroidDriver.cs#L51

**Comment by Dor-bl** [comment]
@seriousQA Regarding the title name, maybe `Setting Up and Running an AppiumDriver Locally for Testing` is a better choice.

**Comment by seriousQA** [comment]
@Dor-bl, thank you for review.
1. "Known issue" section is removed;
2. "AndroidDriver instance" section is updated;
3. "Requirements" section is expanded;
4. The title was changed; links to the wiki page are adjusted; actual title is "Setting Up and Running an AppiumDriver Locally for Testing".

**Comment by Dor-bl** [comment]
@seriousQA awesome! Thanks again for the effort.
@KazuCocoa @jlipps, does the compensation plan include wiki updates as well?
