### ISSUE TITLE
iOSDriver not returning all the available contexts in Appium 5.0.0-rc.2

### ISSUE THREAD

**Issue by openboxmn** [appium/dotnet-client#801]
## Description

When switching from Native view to WebView, calling  Driver.Contexts.ToList() returns only the current context. But when you call the method second time, all the contexts are returned.
## Environment

.Net Framework 4.7.2
Node version v19.6.0
## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
var AppiumDriver = new IOSDriver(TargetUri, AppiumCapabilities);
var context = AppiumDriver.Contexts.ToList();
Actual Result:
context has only the Native_App
Expected Result:
context should have all the available views.

**Comment by KazuCocoa** [comment]
Could you share the appium server log?

It is potentially expected to collect WebView contexts on iOS. It could take time in the first time. Increasing
`appium:webviewConnectTimeout` in capabilities https://appium.github.io/appium-xcuitest-driver/latest/reference/capabilities/ or https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-getcontexts with `waitForWebviewMs` helps for the case.

**Comment by Dor-bl** [comment]
Closed due to no response.

**Comment by SarmadSaleeem** [comment]
Can you tell me which version are you using. In my server log I am getting the correct values. But in my code all contexts returning me these two strings "System.Collections.Generic.Dictionary`2[System.String,System.Object]".

This is from server
[61112fad][XCUITestDriver@edc5] Responding to client with driver.getContexts() result: [{"id":"NATIVE_APP"},{"id":"WEBVIEW_18156.1","title":"Floor Plan","url":"https://devapp.nfsonline.net/AutomationFP/Source=mobile&Functionality=floorplan&Platform=flutter","bundleId":"com.nfs.mobile"}]
