### ISSUE TITLE
Tests execution performance dropped after update to Appium.WebDriver v5.0.0❓ 

### ISSUE THREAD

**Issue by Maosolny** [appium/dotnet-client#803]
Hi everyone 😄 

Have you noticed some tests execution time increase after update to the newest version of Appium.WebDriver❓ 

I mean that each test run slower about 20-30 seconds.

Before that I used WinAppDriver from Microsoft and Appium.WebDriver in version 4.4.5.

Currently, I use Appium 2, appium-windows-driver 2.12.24 and Appium.WebDriver 5.0.0.

I test applications created for Windows (WPF apps exactly).

Thanks for sharing your observations.

**Comment by KazuCocoa** [comment]
Sharing appium server logs in both would help to see the differences between them. e.g. what part could be slower.

**Comment by Dor-bl** [comment]
Closed due to no response.
