### ISSUE TITLE
I seem to not be able to get Horizontal Scrolling to work anymore

### ISSUE THREAD

**Issue by aaronportier** [appium/dotnet-client#816]
I am unable to ensuring its not just a me issue.
Here is the code I am using I thought it worked at one time for Scrolling in the past:
I have not found any type of Swipe that might be  better so I am using the Scroll below.

_driver.FindElement(MobileBy.AndroidUIAutomator("(new UiScrollable(new UiSelector().scrollable(true)).setAsHorizontalList().ScrollIntoView(new UiSelector().text('target fire'))")).Click(); 

Instead it just does nothing or come back with parser issue or missing method name?

**Comment by Dor-bl** [comment]
@aaronportier, Can you please share some appium logs?
Also, the dotnet client version you are using will be helpful.

**Comment by aaronportier** [comment]
After some work I was able to get it to work again. I am stumped with the newest build I egt this wehn i try to run it.     OpenQA.Selenium.WebDriverException : The newSession command returned an unexpected error. Authorization required

**Comment by Dor-bl** [comment]
@aaronportier please provide a snippet of the code and appium logs. It's not clear for what action you receive that error
