### ISSUE TITLE
[Bug]: Unable to inspect element using appium inspector for real device

### ISSUE THREAD

**Issue by ishuvir** [appium/dotnet-client#829]
## Description

Unable to inspect element using appium inspector as appium inspector is failed to capture .

As a user, i have been using and able to inspect element and it was working fine but not sure what happen and its not working now. 

Steps performed: 
1: Started appium server
2: Launched appium inspector and try to start session to inspect 
3: Its keep on spinning but never shows the screenshot of device in appium inspector 
4: I have tried with xcuitest@5.16.1 as earlier it was working on this and also tried after updating  to xcuitest@7.26.4 but not working
5: Tried on  Appium v2.11.3 and also tried on  Appium v2.11.4 version but not working 
6: Also installed new App appium inspector Version: 2024.8.2 

![Screenshot 2024-09-18 at 11 16 33](https://github.com/user-attachments/assets/96ec9190-14b3-4a49-a3ab-6ee03779cf42)

## Environment

* .NET client build version or git revision if you use some snapshot: dotnet --list-sdks
6.0.415 [/usr/local/share/dotnet/sdk]
6.0.417 [/usr/local/share/dotnet/sdk]
6.0.418 [/usr/local/share/dotnet/sdk]
6.0.419 [/usr/local/share/dotnet/sdk]
6.0.420 [/usr/local/share/dotnet/sdk]
6.0.421 [/usr/local/share/dotnet/sdk]
6.0.425 [/usr/local/share/dotnet/sdk]
7.0.309 [/usr/local/share/dotnet/sdk]
7.0.311 [/usr/local/share/dotnet/sdk]
7.0.312 [/usr/local/share/dotnet/sdk]
7.0.313 [/usr/local/share/dotnet/sdk]
7.0.314 [/usr/local/share/dotnet/sdk]
7.0.315 [/usr/local/share/dotnet/sdk]
7.0.317 [/usr/local/share/dotnet/sdk]
8.0.401 [/usr/local/share/dotnet/sdk]

* Appium server version or git revision if you use some snapshot: Tried on  Appium v2.11.3 and also tried on  Appium v2.11.4 version but not working 
* Desktop OS/version used to run Appium if necessary: Sonoma 14.6.1 
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v21.6.2
* Mobile platform/version under test: 17.6.1 version iOS
* Real device or emulator/simulator: real device only (working with simulator)

## Code To Reproduce Issue [ Good To Have ]
I just tried to inspect and it not working

![Screenshot 2024-09-18 at 11 22 39](https://github.com/user-attachments/assets/8271429a-1424-4f14-8b27-94c32c567492)

## Link to Appium logs

appium logs link : https://gist.github.com/ishuvir/d5068827bf86d5a58afd016a0a12f70f

**Comment by Dor-bl** [comment]
I don't see how it's related to dotnet client. Please open the issue on the inspector repository. @eglitise fyi

**Comment by mykola-mokhnach** [comment]
This happens because the installed WDA version is not compatible with the latest iOS. Check https://github.com/appium/appium/issues/20239#issuecomment-2277352021

**Comment by KazuCocoa** [comment]
Closing since this is Xcode 16 related thing as https://github.com/appium/appium/issues/20239#issuecomment-2277352021
